### ISSUE TITLE
Intermittent failures

### ISSUE THREAD

**Issue by hainest** [dyninst/testsuite#132]
## ARM
`test_thread_5` is intermittently hanging on Zeroah. The most common case where the hang is seen is `test_thread_5 g++ dynamiclink create pic`. I've not seen any hangs or crashes on arm1.cs.rice.edu. I've [skipped](https://github.com/dyninst/testsuite/pull/131) this test for now, and the test suite is running to [completion](https://bottle.cs.wisc.edu/details/306). `pc_irpc gcc dynamiclink attach nonpic` hanged on Zeroah- a variant of which has crashed on [Power9](https://bottle.cs.wisc.edu/results/CRASHED/295).

## x86
`test_thread_{1,3,8}` is intermittently failing on x86.

On coriander, [260](https://bottle.cs.wisc.edu/details/260) failed on `test_thread_1`, but just re-running passes ([265](https://bottle.cs.wisc.edu/details/265)). [269](https://bottle.cs.wisc.edu/results/CRASHED/269) crashes on `test_thread_8`; running master (which contains this PR) passes ([274](https://bottle.cs.wisc.edu/details/274)).

On GalacticCentralPoint, [261](https://bottle.cs.wisc.edu/details/261) crashes on `test_thread_3`, but running on master (which contains this PR) passes ([271](https://bottle.cs.wisc.edu/details/271)). Another is [303](https://bottle.cs.wisc.edu/details/303) and just rerunning passes ([304](https://bottle.cs.wisc.edu/details/304)).

The most common error seen in the logs is SIGSEGV.

## Power
Power8 appears to be impervious, but Power9 has seen one failure ([295](https://bottle.cs.wisc.edu/details/295)) where re-running succeeds ([298](https://bottle.cs.wisc.edu/details/298)).

**Comment by hainest** [comment]
@mxz297 In testing #83, I found that the `--no-undefined` linker flag added from the Dyninst [cmake/optimizations.cmake](https://github.com/dyninst/dyninst/blob/master/cmake/optimization.cmake#L23) caused link errors in `libtest12.so`:

>libTest12.c:63: undefined reference to `DYNINSTuserMessage'

which is provided as an [external stub](https://github.com/dyninst/testsuite/blob/master/src/dyninst/libTest12.c#L44) in the source. I really feel this should include the proper header from Dyninst and then link against it correctly as the current situation could cause sporadic errors with handling user messages (sound familiar?). Is there a reason that `libtest12.so` wouldn't be explicitly linked against `libDyninstAPI_RT.so`?

**Comment by mxz297** [comment]
@hainest Agree. This looks strange. I am not aware of this problem. `DYNINSTuserMessage` is declared at

https://github.com/dyninst/dyninst/blob/master/dyninstAPI_RT/h/dyninstRTExport.h#L59

So, you should be able to just include dyninstRTExport.h and link against dyninstAPI_RT.so.

**Comment by hainest** [comment]
On my home machine, I ran test_thread_3 using the same build of Dyninst and the test suite twenty times each, and got it to crash once. The stack trace shows a null pointer access in libpthread. The core dump analysis is below.

    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    Core was generated by `test_thread_3.dyn_g++_64_pic_none -log tmp.log -humanlog - -run test_thread_3'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x0000000000000000 in ?? ()
    [Current thread is 1 (Thread 0x7f2ba2410700 (LWP 27275))]

    (gdb) bt
    #0  0x0000000000000000 in ?? ()
    #1  0x00007f2ba0d3841e in __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at pthread_create.c:675
    #2  0x000055d78f63ca68 in createThreads (num=10, tmain=0x55d78f63c712 <thread_main4(void*)>, tbuf=0x55d78f840300 <test4_threads>)
        at /home/tim/paradyn/UDfAzQnw/testsuite/src/src/dyninst/test_thread.c:108
    #3  0x000055d78f63c7f4 in func4_1 () at /home/tim/paradyn/UDfAzQnw/testsuite/src/src/dyninst/test_thread_3_mutatee.c:85
    #4  0x000055d78f63c846 in test_thread_3_mutatee () at /home/tim/paradyn/UDfAzQnw/testsuite/src/src/dyninst/test_thread_3_mutatee.c:93
    #5  0x000055d78f63c63d in main (iargc=7, argv=0x7ffc774da688) at /home/tim/paradyn/UDfAzQnw/testsuite/src/src/mutatee_driver.c:431
